title: Create | Discover | Inspire
author: Digifaire
email: support@digifaire.com
description: > # this means to ignore newlines until "show_excerpts:"
| As professional technical services experts, crafting solutions brings us joy. 
| From cloud computing applications to engaging the audience, we are happy to build elegant tools and techniques.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: digifaire
    github:  digifaire
    rss: rss
    # dribbble: digifaire
    # facebook: simplyfluff
    # flickr:   digifaire
    # instagram: digifaire
    # linkedin: digifaire
    # pinterest: digifaire
    # youtube: digifaire
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram:
    # googleplus: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance:

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
