title: Digifaire
masthead: /assets/my_masthead.jpg
author: Create | Discover | Inspire
email: support @ digifaire.com
description: > # this means to ignore newlines until "show_excerpts:"
  Digifaire Stack Apps

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: digifaire
    github:  digifaire
    # rss: rss
    # dribbble: digifaire
    facebook: simplyfluff
    # flickr:   digifaire
    instagram: digifaire
    linkedin: raj-digifaire
    # pinterest: digifaire
    # youtube: licenseacademy
    # youtube_channel: licenseacademy
    # youtube_channel_name: hear!hear!
    # telegram:
    # googleplus: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance:

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 #- jekyll-paginate

gems: 
 - jekyll-paginate

  #paginate: 10
  #paginate_path: "/page:num/"
 #pagination:  
 # per_page: 3
 # paginate_path: "/blog/page:num/"
  
  #pagination:
  #enabled: true
  #per_page: 3
  
  #permalink: '/page/:num/'
  #title_suffix: ' - page :num'
  #limit: 0
  #sort_field: 'date'
  #sort_reverse: true
  
  # Produces a cleaner folder structure when using categories
  #permalink: /:year/:month/:title.html
